function options = rusOps(validation)


maxEpochs = 30;
batchSize = 30;
initialLearnRate = 0.3;
validationFreq = 50;
lRateDrop = 0.827;
improveIterations = 160;
dropPeriod = 1;
%path = 'C:\Users\SORENMC\OneDrive - Danmarks Tekniske Universitet\SeriousBuissness\DTU\6. semester\BachelorProjektGit\Code';
if(nargin < 2)
    L2Reg = 0.001;
end


options = trainingOptions(...
    'sgdm',...
    'Momentum',0.95,...
    'MaxEpochs',maxEpochs,...
    'MiniBatchSize',batchSize,...
    'Verbose',1,...
    'ValidationData',validation, ...
    'ValidationPatience',inf,...
    'InitialLearnRate',initialLearnRate, ...
    'ValidationFrequency',validationFreq, ...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropFactor',lRateDrop,...
    'LearnRateDropPeriod',dropPeriod,...
    'Shuffle','every-epoch', ...
    'ExecutionEnvironment','gpu');
%'L2Regularization',L2Reg,...












end